[metadata]
format = { version = "1.1" }

[versions]
indra = "3.1.3"
minecraft = "26.1.2"
vineflower = "1.11.2"
cuiProtocol = "4.0.3"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
neoforge = { module = "net.neoforged:neoforge", version = "26.1.2.75"}
vineflower = { module = "org.vineflower:vineflower", version.ref = "vineflower" }

[plugins]
architecturyPlugin = { id = "architectury-plugin", version = "3.5.163" }
curseForgeGradle = { id = "net.darkhax.curseforgegradle", version = "1.1.26" }
indra-git = { id = "net.kyori.indra.git", version.ref = "indra" }
indra-spotlessLicenser = { id = "net.kyori.indra.licenser.spotless", version.ref = "indra" }
jvmConflictResolution = { id = "org.gradlex.jvm-dependency-conflict-resolution", version = "2.1.2" }
loom = { id = "dev.architectury.loom-no-remap", version = "1.14.471" }
minotaur = { id = "com.modrinth.minotaur", version = "2.8.7" }
publishGithubRelease = { id = "ca.stellardrift.publish-github-release", version = "0.1.0" }
shadow = { id = "com.gradleup.shadow", version = "8.3.5" }
spotless = { id = "com.diffplug.spotless", version = "6.25.0" }
versions = { id = "com.github.ben-manes.versions", version = "0.51.0" }

[libraries.cuiProtocol-common]
module = "org.enginehub.worldeditcui-protocol:worldeditcui-protocol-common-mc26.1"
version.ref = "cuiProtocol"

[libraries.cuiProtocol-fabric]
module = "org.enginehub.worldeditcui-protocol:worldeditcui-protocol-fabric-mc26.1"
version.ref = "cuiProtocol"

[libraries.cuiProtocol-neoforge]
module = "org.enginehub.worldeditcui-protocol:worldeditcui-protocol-neoforge-mc26.1"
version.ref = "cuiProtocol"
